<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Version>1.0.3</Version>
        <AssemblyVersion>1.0.3</AssemblyVersion>
        <FileVersion>1.0.3</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.3" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
        <PackageReference Include="ReactiveUI" Version="24.2.0" />
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
        <PackageReference Include="WebDav.Client" Version="2.9.0" />
    </ItemGroup>
</Project>